apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekscluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
    ssh:
        publicKeyName: Clusterkey
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
        publicKeyName: Clusterkey






